### ISSUE TITLE
is multithreading writing allowed？

### ISSUE THREAD

**Issue by ladyfish** [Esri/file-geodatabase-api#1]
can i ask if i create features on multithreading or multiprocessing，the gdb file ，which i handled on，will be bad，right？

**Comment by frett27** [comment]
Not supported, in but we experienced some working cases using different table (synchronized access), 
on windows OK, in linux, error cases may hang the process (need to synchronize the error handling).

**Comment by lshipman** [comment]
The file geodatabase API does not support multithreading.
