### ISSUE TITLE
.NET Core Support

### ISSUE THREAD

**Issue by qcc-na** [Esri/file-geodatabase-api#25]
Can this be updated to support .NET core?

**Comment by jpritchard-isl** [comment]
I concur this would be very helpful as we move the majority of our apps to .NET Core. A .NET Standard FileGDB library would allow use to continue supporting FGDB in the future.

**Comment by lshipman** [comment]
Currently there are no plans to support ,NET code library in the file geodatabase API. You are welcome to add your vote to the issue on GeoNet. https://community.esri.com/ideas/13220-add-net-core-support-or-mono-support-for-file-geodatabase-api

**Comment by qcc-na** [comment]
Can this be reopened give that .net 6 has been released?  I think many people would appreciate some new bindings.
