### ISSUE TITLE
Will the .NET bindings work on Linux?

### ISSUE THREAD

**Issue by donnyv** [Esri/file-geodatabase-api#5]
Curious if the .NET bindings will work on Linux with either Mono or .NET Core? A lot .NET work is happening on Linux.

**Comment by lshipman** [comment]
We have not tested the .NET bindings on Linux. We will investigate.

**Comment by lshipman** [comment]
After a quick look it may be possible. We have a very small team and significant other priorities, so I can't make any promises on certification of using the .NET bindings on Mono or other. We will see. If it's implortent to you add it to ESRI Ideas https://geonet.esri.com/community/arcgis-ideas/
