### ISSUE TITLE
Access Violation in EnumRows

### ISSUE THREAD

**Issue by genergabasa** [Esri/file-geodatabase-api#52]
Hello, anyone knows how to fix? It happens when I'm loading a certain GDB folder.

Hello, I'm encountering an access violation when calling EnumRows.Next. It happens when I'm loading the attachedn GDB folder. Any ideas?

Exception thrown at 0x00007FFE19D3BC60 (FileGDBAPID.dll) in Samples.exe: 0xC0000005: Access violation reading location 0x000001C48DFF1000.

**Comment by Pat28** [comment]
Same here, unless I do not retrieve the shape, then there is no issue.
Getting the shape contents gives the error, pretty randomly, sometimes after 162 rows, sometimes after 512 rows.
I also tested your FileGDB in QGIS and it shows strange artifacts.

![image](https://github.com/Esri/file-geodatabase-api/assets/2316171/ff55d947-ee5b-4af7-b57c-5042bb2f995b)

**Comment by genergabasa** [comment]
Hi @Pat28 , just solved my issue. Our GDB exporter caused the crash on import due to empty ShapeBuffer set in Row.SetGeometry.

**Comment by Pat28** [comment]
Ah, that explains why rendering in QGIS and other applications did work, probably because the empty entry was not part of the spatial index and hence, ignored.

**Comment by genergabasa** [comment]
I think EnumRows.Next should throw an exemption when the geometry is empty so that we can catch it.
