### ISSUE TITLE
filegdb api 1.5 32bit gcc link is broken or unavailable

### ISSUE THREAD

**Issue by saultdon** [Esri/file-geodatabase-api#6]
Can't seem to download the linux tarball for the 32bit version that compiles against gcc>=5.1

https://github.com/Esri/file-geodatabase-api/blob/master/FileGDB_API_1.5/FileGDB_API_1_5_32gcc51.tar.gz
> Error 503 first byte timeout
> 
> first byte timeout
> 
> Guru Mediation:
> 
> Details: cache-sea1039-SEA 1489075434 2337190757
> 
> Varnish cache server

**Comment by lshipman** [comment]
I'll take a look.

**Comment by saultdon** [comment]
Great, it's back to working now.
