### ISSUE TITLE
wont run on server 2008 

### ISSUE THREAD

**Issue by southmeadows** [Esri/file-geodatabase-api#8]
I developed on a Win 7 machine and all works well for testing. I made a setup and included the system*.dll files as well as the ESRI dll files.  

Framework is installed and is the same version. 

The app is a command line app
It immediately crashes. I have a console writeln at the very start and that doesnt come up either. I have tried x64 and x32 and different frameworks. 

Any ideas?

**Comment by lshipman** [comment]
Lance

On May 21, 2017, at 9:46 AM, Mark <notifications@github.com<mailto:notifications@github.com>> wrote:


I developed on a Win 7 machine and all works well for testing. I made a setup and included the system*.dll files as well as the ESRI dll files.

Framework is installed and is the same version.

The app is a command line app
It immediately crashes. I have a console writeln at the very start and that doesnt come up either. I have tried x64 and x32 and different frameworks.

Any ideas?

-
